LIBFLEXPATH=/Users/jonathanlim/Documents/Compiler/libflex
CONFIGPATH=/Users/jonathanlim/Documents/Compiler/libflex
COMPILERVARIANT=x86_64.clang
OSTYPE=darwin
include		$(CONFIGPATH)/config.$(OSTYPE)-$(COMPILERVARIANT)
include		config.$(OSTYPE)-$(COMPILERVARIANT)

MAKEFLAGS	+= -j

CCFLAGS		= $(PLATFORM_DBGFLAGS) $(PLATFORM_CFLAGS) $(PLATFORM_DFLAGS) $(PLATFORM_OPTFLAGS)
LDFLAGS 	= $(PLATFORM_DBGFLAGS) -lm $(PLATFORM_LFLAGS) 

LIBNOISYCONFIG	= NoisyConfig
NOISYCONFIG_L10N	= EN

#	-std=gnu99 because we use anonymous unions and induction variable defintions in loop head.
CCFLAGS		+= -std=gnu99 -DkNoisyConfigL10N="\"$(NOISYCONFIG_L10N)\"" -DNOISYCONFIG_L10N_EN

TARGET		= noisyconfig-$(OSTYPE)-$(NOISYCONFIG_L10N)

WFLAGS		= -Wall -Werror
INCDIRS		= -I. -I$(LIBFLEXPATH)

NOISYCONFIGEXTENSION	= nc

SOURCES		=\
		main.c                               \
		noisyconfig-tokens.c\
		noisyconfig-lexer.c                  \
		noisyconfig-typeSignatures.c\
		noisyconfig-firstAndFollow.c         \
		noisyconfig-parser.c                 \
		noisyconfig-productions.c            \
		noisyconfig.c\
		noisyconfig-irPass-dotBackend.c      \
		version.c\
		noisyconfig-symbolTable.c\
		noisyconfig-irPass-helpers.c\
		noisyconfig-irHelpers.c\
		noisyconfig-parser-helper.c\
		noisyconfig-primenumbers.c\
		noisyconfig-errors$(NOISYCONFIG_L10N).c\
		noisyconfig-ffi2code-autoGeneratedSets.c\


#
#	Clang seems to be unable to do LTO unless we have all the objects
#	not tucked into a library, so we don't just simply link maain against
#	-l$(LIBNOISY)-$(OSTYPE)-$(NOISYCONFIG_L10N)
#
OBJS		=\
		version.$(OBJECTEXTENSION)\
		main.$(OBJECTEXTENSION)                               \
		noisyconfig-primenumbers.$(OBJECTEXTENSION)\
		noisyconfig-tokens.$(OBJECTEXTENSION)\
		noisyconfig-lexer.$(OBJECTEXTENSION)                  \
		noisyconfig-typeSignatures.$(OBJECTEXTENSION)\
		noisyconfig-firstAndFollow.$(OBJECTEXTENSION)         \
		noisyconfig-parser.$(OBJECTEXTENSION)                 \
		noisyconfig-productions.$(OBJECTEXTENSION)            \
		noisyconfig.$(OBJECTEXTENSION)\
		noisyconfig-irPass-dotBackend.$(OBJECTEXTENSION)      \
		noisyconfig-symbolTable.$(OBJECTEXTENSION)\
		noisyconfig-irPass-helpers.$(OBJECTEXTENSION)\
		noisyconfig-irHelpers.$(OBJECTEXTENSION)\
		noisyconfig-errors$(NOISYCONFIG_L10N).$(OBJECTEXTENSION)\
		noisyconfig-parser-helper.$(OBJECTEXTENSION)\
		noisyconfig-ffi2code-autoGeneratedSets.$(OBJECTEXTENSION)\


LIBNOISYCONFIGOBJS =\
		version.$(OBJECTEXTENSION)\
		noisyconfig-lexer.$(OBJECTEXTENSION)                  \
		noisyconfig-primenumbers.$(OBJECTEXTENSION)\
		noisyconfig-typeSignatures.$(OBJECTEXTENSION)\
		noisyconfig-firstAndFollow.$(OBJECTEXTENSION)         \
		noisyconfig-parser.$(OBJECTEXTENSION)                 \
		noisyconfig-productions.$(OBJECTEXTENSION)            \
		noisyconfig.$(OBJECTEXTENSION)\
		noisyconfig-irPass-dotBackend.$(OBJECTEXTENSION)      \
		noisyconfig-tokens.$(OBJECTEXTENSION)\
		noisyconfig-symbolTable.$(OBJECTEXTENSION)\
		noisyconfig-irPass-helpers.$(OBJECTEXTENSION)\
		noisyconfig-irHelpers.$(OBJECTEXTENSION)\
		noisyconfig-errors$(NOISYCONFIG_L10N).$(OBJECTEXTENSION)\
		noisyconfig-parser-helper.$(OBJECTEXTENSION)\
		noisyconfig-ffi2code-autoGeneratedSets.$(OBJECTEXTENSION)\



HEADERS		=\
		$(LIBFLEXPATH)/flex.h\
		version.h\
		noisyconfig-errors.h                 \
		noisyconfig-firstAndFollow.h         \
		noisyconfig-lexer.h                  \
		noisyconfig-irPass-dotBackend.h      \
		noisyconfig-parser.h                 \
		noisyconfig.h\
		noisyconfig-irPass-helpers.h         \
		noisyconfig-irHelpers.h\
		noisyconfig-parser-helper.h         \
		noisyconfig-errors.h\



all: lib$(LIBNOISYCONFIG)-$(OSTYPE)-$(NOISYCONFIG_L10N).a target $(CONFIGPATH)/config.$(OSTYPE)-$(MACHTYPE)$(COMPILERVARIANT) config.$(OSTYPE)-$(MACHTYPE)$(COMPILERVARIANT) Makefile


#
#			Libraries
#
lib$(LIBNOISYCONFIG)-$(OSTYPE)-$(NOISYCONFIG_L10N).a: $(LIBNOISYCONFIGOBJS) $(CONFIGPATH)/config.$(OSTYPE)-$(MACHTYPE)$(COMPILERVARIANT) config.$(OSTYPE)-$(MACHTYPE)$(COMPILERVARIANT) Makefile 
	$(AR) $(ARFLAGS) $@ $(LIBNOISYCONFIGOBJS)


#
#			Executables
#
target: $(OBJS) $(CONFIGPATH)/config.$(OSTYPE)-$(MACHTYPE)$(COMPILERVARIANT) config.$(OSTYPE)-$(MACHTYPE)$(COMPILERVARIANT) Makefile 
	$(LD) -L. -L$(LIBFLEXPATH) $(LDFLAGS) $(OBJS) -lflex-$(OSTYPE) -lm -o $(TARGET)



#
#			Objects
#
%.$(OBJECTEXTENSION): %.c $(HEADERS) $(CONFIGPATH)/config.$(OSTYPE)-$(MACHTYPE)$(COMPILERVARIANT) config.$(OSTYPE)-$(MACHTYPE)$(COMPILERVARIANT) Makefile 
	$(CC) $(FLEXFLAGS) $(INCDIRS) $(CCFLAGS) $(WFLAGS) $(OPTFLAGS) -c $(LINTFLAGS) $<
	$(CC) $(FLEXFLAGS) $(INCDIRS) $(CCFLAGS) $(WFLAGS) $(OPTFLAGS) -c $<


version.c: $(HEADERS) Makefile
	echo 'char kNoisyConfigVersion[] = "0.1-alpha-'`git rev-list --count HEAD`' ('`git rev-parse HEAD`') (build '`date '+%m-%d-%Y-%H:%M'`-`whoami`@`hostname -s`-`uname -s`-`uname -r`-`uname -m`\)\"\; > version.c



clean:
	rm -rf version.c $(OBJS) $(CGIOBJS) $(LIBNOISYCONFIGOBJS) $(TARGET) $(TARGET).dSYM $(CGI_TARGET) $(CGI_TARGET).dsym lib$(LIBNOISYCONFIG)-$(OSTYPE)-$(NOISYCONFIG_L10N).a *.o *.plist 
