LIBFLEXPATH=/Users/jonathanlim/Documents/Compiler/libflex
CONFIGPATH=/Users/jonathanlim/Documents/Compiler/libflex
MACHTYPE=x86_64
COMPILERVARIANT=clang
OSTYPE=darwin
include		$(CONFIGPATH)/config.$(OSTYPE)-$(MACHTYPE).$(COMPILERVARIANT)
include		common/config.$(OSTYPE)-$(MACHTYPE).$(COMPILERVARIANT)

MAKEFLAGS	+= -j

CCFLAGS		= $(PLATFORM_DBGFLAGS) $(PLATFORM_CFLAGS) $(PLATFORM_DFLAGS) $(PLATFORM_OPTFLAGS)
LDFLAGS 	= $(PLATFORM_DBGFLAGS) -lm $(PLATFORM_LFLAGS) `pkg-config --libs 'libprotobuf-c >= 1.0.0'`

LIBNOISY	= Noisy
NOISY_L10N	= EN

#	-std=gnu99 because we use anonymous unions and induction variable defintions in loop head.
CCFLAGS		+= -std=gnu99 -DkNoisyL10N="\"$(NOISY_L10N)\"" -DNOISY_L10N_EN

TARGET		= noisy-$(OSTYPE)-$(NOISY_L10N)
CGI_TARGET	= common/noisycgi-$(OSTYPE)-$(NOISY_L10N)

WFLAGS		= -Wall -Werror
INCDIRS		= -I. -I$(LIBFLEXPATH)
PROTOC		= protoc-c

NOISYEXTENSION	= n
NEWTONEXTENSION	= nt

SOURCES		=\
		common/version.c\
		noisy/noisy.pb-c.c\
		common/main.c\
		common/cgimain.c\
		noisy/noisy.c\
		noisy/noisy-errors$(NOISY_L10N).c\
		noisy/noisy-typeSignatures.c\
		noisy/noisy-productions.c\
		noisy/noisy-tokens.c\
		noisy/noisy-timeStamps.c\
		noisy/noisy-types.c\
		noisy/noisy-lexer.c\
		noisy/noisy-lexers-helpers.c\
		noisy/noisy-parser.c\
		noisy/noisy-firstAndFollow.c\
		noisy/noisy-irHelpers.c\
		noisy/noisy-ffi2code-autoGeneratedSets.c\
		noisy/noisy-symbolTable.c\
		noisy/noisy-irPass-dotBackend.c\
		noisy/noisy-irPass-protobufBackend.c\
		newton/newton-tokens.c\
		newton/newton-lexer.c                  \
		newton/newton-firstAndFollow.c         \
		newton/newton-parser.c                 \
		newton/newton-parser-expression.c                 \
		newton/newton-symbolTable.c\
		newton/newton-primenumbers.c\
		newton/newton-ffi2code-autoGeneratedSets.c\


#
#	Clang seems to be unable to do LTO unless we have all the objects
#	not tucked into a library, so we don't just simply link maain against
#	-l$(LIBNOISY)-$(OSTYPE)-$(NOISY_L10N)
#
OBJS		=\
		common/version.$(OBJECTEXTENSION)\
		noisy/noisy.pb-c.$(OBJECTEXTENSION)\
		noisy/noisy-errors$(NOISY_L10N).$(OBJECTEXTENSION)\
		noisy/noisy-typeSignatures.$(OBJECTEXTENSION)\
		noisy/noisy-productions.$(OBJECTEXTENSION)\
		noisy/noisy-tokens.$(OBJECTEXTENSION)\
		noisy/noisy-timeStamps.$(OBJECTEXTENSION)\
		noisy/noisy.$(OBJECTEXTENSION)\
		noisy/noisy-types.$(OBJECTEXTENSION)\
		noisy/noisy-lexers-helpers.$(OBJECTEXTENSION)\
		noisy/noisy-lexer.$(OBJECTEXTENSION)\
		noisy/noisy-parser.$(OBJECTEXTENSION)\
		noisy/noisy-firstAndFollow.$(OBJECTEXTENSION)\
		noisy/noisy-ffi2code-autoGeneratedSets.$(OBJECTEXTENSION)\
		noisy/noisy-irHelpers.$(OBJECTEXTENSION)\
		noisy/noisy-irPass-helpers.$(OBJECTEXTENSION)\
		noisy/noisy-symbolTable.$(OBJECTEXTENSION)\
		noisy/noisy-irPass-dotBackend.$(OBJECTEXTENSION)\
		noisy/noisy-irPass-protobufBackend.$(OBJECTEXTENSION)\
		common/main.$(OBJECTEXTENSION)\
		newton/newton-primenumbers.$(OBJECTEXTENSION)\
		newton/newton-tokens.$(OBJECTEXTENSION)\
		newton/newton-lexer.$(OBJECTEXTENSION)                  \
		newton/newton-firstAndFollow.$(OBJECTEXTENSION)         \
		newton/newton-parser.$(OBJECTEXTENSION)                 \
		newton/newton-parser-expression.$(OBJECTEXTENSION)                 \
		newton/newton-symbolTable.$(OBJECTEXTENSION)\
		newton/newton-ffi2code-autoGeneratedSets.$(OBJECTEXTENSION)\


#
#	Clang seems to be unable to do LTO unless we have all the objects
#	not tucked into a library, so we don't just simply link maain against
#	-l$(LIBNOISY)-$(OSTYPE)-$(NOISY_L10N)
#
CGIOBJS		=\
		common/version.$(OBJECTEXTENSION)\
		noisy/noisy.pb-c.$(OBJECTEXTENSION)\
		noisy/noisy-errors$(NOISY_L10N).$(OBJECTEXTENSION)\
		noisy/noisy-typeSignatures.$(OBJECTEXTENSION)\
		noisy/noisy-productions.$(OBJECTEXTENSION)\
		noisy/noisy-tokens.$(OBJECTEXTENSION)\
		noisy/noisy-timeStamps.$(OBJECTEXTENSION)\
		noisy/noisy.$(OBJECTEXTENSION)\
		noisy/noisy-types.$(OBJECTEXTENSION)\
		noisy/noisy-lexer.$(OBJECTEXTENSION)\
		noisy/noisy-lexers-helpers.$(OBJECTEXTENSION)\
		noisy/noisy-parser.$(OBJECTEXTENSION)\
		noisy/noisy-firstAndFollow.$(OBJECTEXTENSION)\
		noisy/noisy-ffi2code-autoGeneratedSets.$(OBJECTEXTENSION)\
		noisy/noisy-irHelpers.$(OBJECTEXTENSION)\
		noisy/noisy-irPass-helpers.$(OBJECTEXTENSION)\
		noisy/noisy-symbolTable.$(OBJECTEXTENSION)\
		noisy/noisy-irPass-dotBackend.$(OBJECTEXTENSION)\
		noisy/noisy-irPass-protobufBackend.$(OBJECTEXTENSION)\
		common/cgimain.$(OBJECTEXTENSION)\
		newton/newton-primenumbers.$(OBJECTEXTENSION)\
		newton/newton-tokens.$(OBJECTEXTENSION)\
		newton/newton-lexer.$(OBJECTEXTENSION)                  \
		newton/newton-firstAndFollow.$(OBJECTEXTENSION)         \
		newton/newton-parser.$(OBJECTEXTENSION)                 \
		newton/newton-parser-expression.$(OBJECTEXTENSION)                 \
		newton/newton-symbolTable.$(OBJECTEXTENSION)\
		newton/newton-ffi2code-autoGeneratedSets.$(OBJECTEXTENSION)\


LIBNOISYOBJS =\
		common/version.$(OBJECTEXTENSION)\
		noisy/noisy.pb-c.$(OBJECTEXTENSION)\
		noisy/noisy-errors$(NOISY_L10N).$(OBJECTEXTENSION)\
		noisy/noisy-typeSignatures.$(OBJECTEXTENSION)\
		noisy/noisy-productions.$(OBJECTEXTENSION)\
		noisy/noisy-tokens.$(OBJECTEXTENSION)\
		noisy/noisy-timeStamps.$(OBJECTEXTENSION)\
		noisy/noisy.$(OBJECTEXTENSION)\
		noisy/noisy-types.$(OBJECTEXTENSION)\
		noisy/noisy-lexer.$(OBJECTEXTENSION)\
		noisy/noisy-lexers-helpers.$(OBJECTEXTENSION)\
		noisy/noisy-parser.$(OBJECTEXTENSION)\
		noisy/noisy-firstAndFollow.$(OBJECTEXTENSION)\
		noisy/noisy-ffi2code-autoGeneratedSets.$(OBJECTEXTENSION)\
		noisy/noisy-irHelpers.$(OBJECTEXTENSION)\
		noisy/noisy-irPass-helpers.$(OBJECTEXTENSION)\
		noisy/noisy-symbolTable.$(OBJECTEXTENSION)\
		noisy/noisy-irPass-dotBackend.$(OBJECTEXTENSION)\
		noisy/noisy-irPass-protobufBackend.$(OBJECTEXTENSION)\
		newton/newton-primenumbers.$(OBJECTEXTENSION)\
		newton/newton-tokens.$(OBJECTEXTENSION)\
		newton/newton-lexer.$(OBJECTEXTENSION)                  \
		newton/newton-firstAndFollow.$(OBJECTEXTENSION)         \
		newton/newton-parser.$(OBJECTEXTENSION)                 \
		newton/newton-parser-expression.$(OBJECTEXTENSION)                 \
		newton/newton-symbolTable.$(OBJECTEXTENSION)\
		newton/newton-ffi2code-autoGeneratedSets.$(OBJECTEXTENSION)\


HEADERS		=\
		$(LIBFLEXPATH)/flex.h\
		common/version.h\
		noisy/noisy.pb-c.h\
		noisy/noisy.h\
		noisy/noisy-errors.h\
		noisy/noisy-timeStamps.h\
		noisy/noisy-types.h\
		noisy/noisy-lexer.h\
		noisy/noisy-lexers-helpers.h\
		noisy/noisy-parser.h\
		noisy/noisy-irHelpers.h\
		noisy/noisy-irPass-helpers.h\
		noisy/noisy-firstAndFollow.h\
		noisy/noisy-symbolTable.h\
		noisy/noisy-irPass-dotBackend.h\
		noisy/noisy-irPass-protobufBackend.h\
		newton/newton-firstAndFollow.h         \
		newton/newton-lexer.h                  \
		newton/newton-parser.h                 \
		newton/newton-parser-expression.h                 \



all: installhooks lib$(LIBNOISY)-$(OSTYPE)-$(NOISY_L10N).a target $(CONFIGPATH)/config.$(OSTYPE)-$(MACHTYPE).$(COMPILERVARIANT) common/config.$(OSTYPE)-$(MACHTYPE).$(COMPILERVARIANT) Makefile cgi

#
#			Install the pre-commit hooks. There doesn't seem to be any other way to force people to install the hook when comitting on Noisy.
#
installhooks:
	cp precommitStatisticsHook.sh .git/hooks/pre-commit
	cp postcommitStatisticsHook.sh .git/hooks/post-commit
	chmod +x .git/hooks/pre-commit
	chmod +x .git/hooks/post-commit


#
#			Libraries
#
lib$(LIBNOISY)-$(OSTYPE)-$(NOISY_L10N).a: $(LIBNOISYOBJS) $(CONFIGPATH)/config.$(OSTYPE)-$(MACHTYPE).$(COMPILERVARIANT) common/config.$(OSTYPE)-$(MACHTYPE).$(COMPILERVARIANT) Makefile 
	$(AR) $(ARFLAGS) $@ $(LIBNOISYOBJS)


#
#			Executables
#
target: $(OBJS) $(CONFIGPATH)/config.$(OSTYPE)-$(MACHTYPE).$(COMPILERVARIANT) common/config.$(OSTYPE)-$(MACHTYPE).$(COMPILERVARIANT) Makefile 
	$(LD) -L. -L$(LIBFLEXPATH) $(LDFLAGS) $(OBJS) -lflex-$(OSTYPE) -lm -o $(TARGET)


cgi:lib$(LIBNOISY)-$(OSTYPE)-$(NOISY_L10N).a $(CGIOBJS) $(CONFIGPATH)/config.$(OSTYPE)-$(MACHTYPE).$(COMPILERVARIANT) common/config.$(OSTYPE)-$(MACHTYPE).$(COMPILERVARIANT) Makefile 
	$(LD) -L. -L$(LIBFLEXPATH) $(LDFLAGS) $(CGIOBJS) -lflex-$(OSTYPE) -o $(CGI_TARGET)


full: scan README.sloccount


#
#			Objects
#
%.$(OBJECTEXTENSION): %.c $(HEADERS) $(CONFIGPATH)/config.$(OSTYPE)-$(MACHTYPE).$(COMPILERVARIANT) common/config.$(OSTYPE)-$(MACHTYPE).$(COMPILERVARIANT) Makefile 
#	$(SPLINT) $(FLEXFLAGS) $(INCDIRS) $<
#	$(LCLINT) $(FLEXFLAGS) $(INCDIRS) $<
	$(CC) $(FLEXFLAGS) $(INCDIRS) $(CCFLAGS) $(WFLAGS) $(OPTFLAGS) -c $(LINTFLAGS) $<
	$(CC) $(FLEXFLAGS) $(INCDIRS) $(CCFLAGS) $(WFLAGS) $(OPTFLAGS) -c $<

noisy/noisy.pb-c.c: noisy/noisy.proto Makefile
	$(PROTOC) --c_out=. noisy/noisy.proto

noisy/noisy.pb-c.h: noisy/noisy.pb-c.c

noisy/noisy-irPass-protobufBackend.$(OBJECTEXTENSION): noisy/noisy-irPass-protobufBackend.c
	$(CC) $(FLEXFLAGS) $(INCDIRS) $(CCFLAGS) `pkg-config --cflags 'libprotobuf-c >= 1.0.0'` $(WFLAGS) $(OPTFLAGS) -c $<

noisy/noisy.pb-c.$(OBJECTEXTENSION): noisy/noisy.pb-c.c noisy/noisy.proto Makefile
	$(CC) $(FLEXFLAGS) $(INCDIRS) $(CCFLAGS) `pkg-config --cflags 'libprotobuf-c >= 1.0.0'` $(WFLAGS) $(OPTFLAGS) -c $<

common/version.c: $(HEADERS) Makefile
	echo 'char kNoisyVersion[] = "0.1-alpha-'`git rev-list --count HEAD`' ('`git rev-parse HEAD`') (build '`date '+%m-%d-%Y-%H:%M'`-`whoami`@`hostname -s`-`uname -s`-`uname -r`-`uname -m`\)\"\; > common/version.c



scan:	clean
	scan-build --use-cc=$(CC) -k -V make -j4


README.sloccount: $(HEADERS) $(SOURCES)
	sloccount *.c *.h *.grammar *.ffi *.$(NOISYEXTENSION) */*.$(NOISYEXTENSION) > README.sloccount


installcgi: cgi
	sudo cp $(CGI_TARGET) $(CGI_BIN)
	
test:
	./noisy-darwin-EN --dot examples/helloWorld.n | dot -Tpdf -O ; open noname.gv.pdf 


clean:
	rm -rf common/version.c $(OBJS) $(CGIOBJS) $(LIBNOISYOBJS) $(TARGET) $(TARGET).dSYM $(CGI_TARGET) $(CGI_TARGET).dsym lib$(LIBNOISY)-$(OSTYPE)-$(NOISY_L10N).a *.o *.plist noisy/noisy.pb-c.c noisy/noisy.pb-c.h 
