#include <stdlib.h>
#include <stdbool.h>
#include <setjmp.h>
#include <stdint.h>
#include "flextypes.h"
#include "flexerror.h"
#include "flex.h"
#include "noisyconfig-timeStamps.h"
#include "noisyconfig.h"

// this file is deprecated
// look at noisyconfig-ffi2code-autoGeneratedSets.c
