/*
 * Generated by dtrace(1M).
 */

#ifndef	_INVARIANT_PROBES_H
#define	_INVARIANT_PROBES_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define INVARIANT_STABILITY "___dtrace_stability$invariant$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define INVARIANT_TYPEDEFS "___dtrace_typedefs$invariant$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	INVARIANT_INVARIANT_DONE() \
do { \
	__asm__ volatile(".reference " INVARIANT_TYPEDEFS); \
	__dtrace_probe$invariant$invariant__done$v1(); \
	__asm__ volatile(".reference " INVARIANT_STABILITY); \
} while (0)
#define	INVARIANT_INVARIANT_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$invariant$invariant__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	INVARIANT_INVARIANT_START() \
do { \
	__asm__ volatile(".reference " INVARIANT_TYPEDEFS); \
	__dtrace_probe$invariant$invariant__start$v1(); \
	__asm__ volatile(".reference " INVARIANT_STABILITY); \
} while (0)
#define	INVARIANT_INVARIANT_START_ENABLED() \
	({ int _r = __dtrace_isenabled$invariant$invariant__start$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$invariant$invariant__done$v1(void);
extern int __dtrace_isenabled$invariant$invariant__done$v1(void);
extern void __dtrace_probe$invariant$invariant__start$v1(void);
extern int __dtrace_isenabled$invariant$invariant__start$v1(void);

#else

#define	INVARIANT_INVARIANT_DONE() \
do { \
	} while (0)
#define	INVARIANT_INVARIANT_DONE_ENABLED() (0)
#define	INVARIANT_INVARIANT_START() \
do { \
	} while (0)
#define	INVARIANT_INVARIANT_START_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _INVARIANT_PROBES_H */
