//
// Created by ds123 on 2022/6/10.
//

#ifndef NOISY_LANG_COMPILER_INFER_BOUND_CONTROL_FLOW_H
#define NOISY_LANG_COMPILER_INFER_BOUND_CONTROL_FLOW_H

int controlFlowFunc(void);

#endif //NOISY_LANG_COMPILER_INFER_BOUND_CONTROL_FLOW_H
