/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: noisy.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "noisy.pb-c.h"
void   noisy__noisy_source_info__init
                     (Noisy__NoisySourceInfo         *message)
{
  static Noisy__NoisySourceInfo init_value = NOISY__NOISY_SOURCE_INFO__INIT;
  *message = init_value;
}
size_t noisy__noisy_source_info__get_packed_size
                     (const Noisy__NoisySourceInfo *message)
{
  assert(message->base.descriptor == &noisy__noisy_source_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t noisy__noisy_source_info__pack
                     (const Noisy__NoisySourceInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &noisy__noisy_source_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t noisy__noisy_source_info__pack_to_buffer
                     (const Noisy__NoisySourceInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &noisy__noisy_source_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Noisy__NoisySourceInfo *
       noisy__noisy_source_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Noisy__NoisySourceInfo *)
     protobuf_c_message_unpack (&noisy__noisy_source_info__descriptor,
                                allocator, len, data);
}
void   noisy__noisy_source_info__free_unpacked
                     (Noisy__NoisySourceInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &noisy__noisy_source_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   noisy__noisy_ir_node__init
                     (Noisy__NoisyIrNode         *message)
{
  static Noisy__NoisyIrNode init_value = NOISY__NOISY_IR_NODE__INIT;
  *message = init_value;
}
size_t noisy__noisy_ir_node__get_packed_size
                     (const Noisy__NoisyIrNode *message)
{
  assert(message->base.descriptor == &noisy__noisy_ir_node__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t noisy__noisy_ir_node__pack
                     (const Noisy__NoisyIrNode *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &noisy__noisy_ir_node__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t noisy__noisy_ir_node__pack_to_buffer
                     (const Noisy__NoisyIrNode *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &noisy__noisy_ir_node__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Noisy__NoisyIrNode *
       noisy__noisy_ir_node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Noisy__NoisyIrNode *)
     protobuf_c_message_unpack (&noisy__noisy_ir_node__descriptor,
                                allocator, len, data);
}
void   noisy__noisy_ir_node__free_unpacked
                     (Noisy__NoisyIrNode *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &noisy__noisy_ir_node__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   noisy__noisy_token__init
                     (Noisy__NoisyToken         *message)
{
  static Noisy__NoisyToken init_value = NOISY__NOISY_TOKEN__INIT;
  *message = init_value;
}
size_t noisy__noisy_token__get_packed_size
                     (const Noisy__NoisyToken *message)
{
  assert(message->base.descriptor == &noisy__noisy_token__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t noisy__noisy_token__pack
                     (const Noisy__NoisyToken *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &noisy__noisy_token__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t noisy__noisy_token__pack_to_buffer
                     (const Noisy__NoisyToken *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &noisy__noisy_token__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Noisy__NoisyToken *
       noisy__noisy_token__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Noisy__NoisyToken *)
     protobuf_c_message_unpack (&noisy__noisy_token__descriptor,
                                allocator, len, data);
}
void   noisy__noisy_token__free_unpacked
                     (Noisy__NoisyToken *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &noisy__noisy_token__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   noisy__noisy_scope__init
                     (Noisy__NoisyScope         *message)
{
  static Noisy__NoisyScope init_value = NOISY__NOISY_SCOPE__INIT;
  *message = init_value;
}
size_t noisy__noisy_scope__get_packed_size
                     (const Noisy__NoisyScope *message)
{
  assert(message->base.descriptor == &noisy__noisy_scope__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t noisy__noisy_scope__pack
                     (const Noisy__NoisyScope *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &noisy__noisy_scope__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t noisy__noisy_scope__pack_to_buffer
                     (const Noisy__NoisyScope *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &noisy__noisy_scope__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Noisy__NoisyScope *
       noisy__noisy_scope__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Noisy__NoisyScope *)
     protobuf_c_message_unpack (&noisy__noisy_scope__descriptor,
                                allocator, len, data);
}
void   noisy__noisy_scope__free_unpacked
                     (Noisy__NoisyScope *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &noisy__noisy_scope__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   noisy__noisy_symbol__init
                     (Noisy__NoisySymbol         *message)
{
  static Noisy__NoisySymbol init_value = NOISY__NOISY_SYMBOL__INIT;
  *message = init_value;
}
size_t noisy__noisy_symbol__get_packed_size
                     (const Noisy__NoisySymbol *message)
{
  assert(message->base.descriptor == &noisy__noisy_symbol__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t noisy__noisy_symbol__pack
                     (const Noisy__NoisySymbol *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &noisy__noisy_symbol__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t noisy__noisy_symbol__pack_to_buffer
                     (const Noisy__NoisySymbol *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &noisy__noisy_symbol__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Noisy__NoisySymbol *
       noisy__noisy_symbol__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Noisy__NoisySymbol *)
     protobuf_c_message_unpack (&noisy__noisy_symbol__descriptor,
                                allocator, len, data);
}
void   noisy__noisy_symbol__free_unpacked
                     (Noisy__NoisySymbol *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &noisy__noisy_symbol__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   noisy__noisy_state__init
                     (Noisy__NoisyState         *message)
{
  static Noisy__NoisyState init_value = NOISY__NOISY_STATE__INIT;
  *message = init_value;
}
size_t noisy__noisy_state__get_packed_size
                     (const Noisy__NoisyState *message)
{
  assert(message->base.descriptor == &noisy__noisy_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t noisy__noisy_state__pack
                     (const Noisy__NoisyState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &noisy__noisy_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t noisy__noisy_state__pack_to_buffer
                     (const Noisy__NoisyState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &noisy__noisy_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Noisy__NoisyState *
       noisy__noisy_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Noisy__NoisyState *)
     protobuf_c_message_unpack (&noisy__noisy_state__descriptor,
                                allocator, len, data);
}
void   noisy__noisy_state__free_unpacked
                     (Noisy__NoisyState *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &noisy__noisy_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor noisy__noisy_source_info__field_descriptors[5] =
{
  {
    "genealogy",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Noisy__NoisySourceInfo, n_genealogy),
    offsetof(Noisy__NoisySourceInfo, genealogy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fileName",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisySourceInfo, filename),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lineNumber",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisySourceInfo, linenumber),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "columnNumber",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisySourceInfo, columnnumber),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisySourceInfo, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned noisy__noisy_source_info__field_indices_by_name[] = {
  3,   /* field[3] = columnNumber */
  1,   /* field[1] = fileName */
  0,   /* field[0] = genealogy */
  4,   /* field[4] = length */
  2,   /* field[2] = lineNumber */
};
static const ProtobufCIntRange noisy__noisy_source_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor noisy__noisy_source_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Noisy.NoisySourceInfo",
  "NoisySourceInfo",
  "Noisy__NoisySourceInfo",
  "Noisy",
  sizeof(Noisy__NoisySourceInfo),
  5,
  noisy__noisy_source_info__field_descriptors,
  noisy__noisy_source_info__field_indices_by_name,
  1,  noisy__noisy_source_info__number_ranges,
  (ProtobufCMessageInit) noisy__noisy_source_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor noisy__noisy_ir_node__field_descriptors[5] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisyIrNode, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tokenString",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisyIrNode, tokenstring),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sourceInfo",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisyIrNode, sourceinfo),
    &noisy__noisy_source_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "symbol",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisyIrNode, symbol),
    &noisy__noisy_symbol__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nodeColor",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisyIrNode, nodecolor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned noisy__noisy_ir_node__field_indices_by_name[] = {
  4,   /* field[4] = nodeColor */
  2,   /* field[2] = sourceInfo */
  3,   /* field[3] = symbol */
  1,   /* field[1] = tokenString */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange noisy__noisy_ir_node__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 7, 3 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor noisy__noisy_ir_node__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Noisy.NoisyIrNode",
  "NoisyIrNode",
  "Noisy__NoisyIrNode",
  "Noisy",
  sizeof(Noisy__NoisyIrNode),
  5,
  noisy__noisy_ir_node__field_descriptors,
  noisy__noisy_ir_node__field_indices_by_name,
  2,  noisy__noisy_ir_node__number_ranges,
  (ProtobufCMessageInit) noisy__noisy_ir_node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor noisy__noisy_token__field_descriptors[6] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisyToken, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "identifier",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisyToken, identifier),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "integerConst",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Noisy__NoisyToken, has_integerconst),
    offsetof(Noisy__NoisyToken, integerconst),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "realConst",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Noisy__NoisyToken, has_realconst),
    offsetof(Noisy__NoisyToken, realconst),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stringConst",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisyToken, stringconst),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sourceInfo",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisyToken, sourceinfo),
    &noisy__noisy_source_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned noisy__noisy_token__field_indices_by_name[] = {
  1,   /* field[1] = identifier */
  2,   /* field[2] = integerConst */
  3,   /* field[3] = realConst */
  5,   /* field[5] = sourceInfo */
  4,   /* field[4] = stringConst */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange noisy__noisy_token__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor noisy__noisy_token__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Noisy.NoisyToken",
  "NoisyToken",
  "Noisy__NoisyToken",
  "Noisy",
  sizeof(Noisy__NoisyToken),
  6,
  noisy__noisy_token__field_descriptors,
  noisy__noisy_token__field_indices_by_name,
  1,  noisy__noisy_token__number_ranges,
  (ProtobufCMessageInit) noisy__noisy_token__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor noisy__noisy_scope__field_descriptors[5] =
{
  {
    "identifier",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisyScope, identifier),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "childScopes",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Noisy__NoisyScope, n_childscopes),
    offsetof(Noisy__NoisyScope, childscopes),
    &noisy__noisy_scope__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "symbols",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Noisy__NoisyScope, n_symbols),
    offsetof(Noisy__NoisyScope, symbols),
    &noisy__noisy_symbol__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "begin",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisyScope, begin),
    &noisy__noisy_source_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisyScope, end),
    &noisy__noisy_source_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned noisy__noisy_scope__field_indices_by_name[] = {
  3,   /* field[3] = begin */
  1,   /* field[1] = childScopes */
  4,   /* field[4] = end */
  0,   /* field[0] = identifier */
  2,   /* field[2] = symbols */
};
static const ProtobufCIntRange noisy__noisy_scope__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor noisy__noisy_scope__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Noisy.NoisyScope",
  "NoisyScope",
  "Noisy__NoisyScope",
  "Noisy",
  sizeof(Noisy__NoisyScope),
  5,
  noisy__noisy_scope__field_descriptors,
  noisy__noisy_scope__field_indices_by_name,
  1,  noisy__noisy_scope__number_ranges,
  (ProtobufCMessageInit) noisy__noisy_scope__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor noisy__noisy_symbol__field_descriptors[9] =
{
  {
    "identifier",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisySymbol, identifier),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sourceInfo",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisySymbol, sourceinfo),
    &noisy__noisy_source_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "symbolType",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisySymbol, symboltype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scope",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisySymbol, scope),
    &noisy__noisy_scope__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "definition",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisySymbol, definition),
    &noisy__noisy_symbol__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "typeTree",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisySymbol, typetree),
    &noisy__noisy_ir_node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "intConst",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Noisy__NoisySymbol, has_intconst),
    offsetof(Noisy__NoisySymbol, intconst),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "realConst",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Noisy__NoisySymbol, has_realconst),
    offsetof(Noisy__NoisySymbol, realconst),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stringConst",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Noisy__NoisySymbol, stringconst),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned noisy__noisy_symbol__field_indices_by_name[] = {
  4,   /* field[4] = definition */
  0,   /* field[0] = identifier */
  6,   /* field[6] = intConst */
  7,   /* field[7] = realConst */
  3,   /* field[3] = scope */
  1,   /* field[1] = sourceInfo */
  8,   /* field[8] = stringConst */
  2,   /* field[2] = symbolType */
  5,   /* field[5] = typeTree */
};
static const ProtobufCIntRange noisy__noisy_symbol__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor noisy__noisy_symbol__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Noisy.NoisySymbol",
  "NoisySymbol",
  "Noisy__NoisySymbol",
  "Noisy",
  sizeof(Noisy__NoisySymbol),
  9,
  noisy__noisy_symbol__field_descriptors,
  noisy__noisy_symbol__field_indices_by_name,
  1,  noisy__noisy_symbol__number_ranges,
  (ProtobufCMessageInit) noisy__noisy_symbol__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor noisy__noisy_state__field_descriptors[2] =
{
  {
    "noisyIrRoot",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Noisy__NoisyState, n_noisyirroot),
    offsetof(Noisy__NoisyState, noisyirroot),
    &noisy__noisy_ir_node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "noisyIrTopScope",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Noisy__NoisyState, n_noisyirtopscope),
    offsetof(Noisy__NoisyState, noisyirtopscope),
    &noisy__noisy_scope__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned noisy__noisy_state__field_indices_by_name[] = {
  0,   /* field[0] = noisyIrRoot */
  1,   /* field[1] = noisyIrTopScope */
};
static const ProtobufCIntRange noisy__noisy_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor noisy__noisy_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Noisy.NoisyState",
  "NoisyState",
  "Noisy__NoisyState",
  "Noisy",
  sizeof(Noisy__NoisyState),
  2,
  noisy__noisy_state__field_descriptors,
  noisy__noisy_state__field_indices_by_name,
  1,  noisy__noisy_state__number_ranges,
  (ProtobufCMessageInit) noisy__noisy_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
